### ISSUE TITLE
Having problems understanding 

### ISSUE THREAD

**Issue by dejifemi** [WebDevSimplified/Face-Detection-JavaScript#1]
Hello, on your Youtube channel you didn't explain how the code connects to the API. if you clone or download it from GitHub.. maybe install or something. Please help.

**Comment by WebDevSimplified** [comment]
All of the code for the application is in the GitHub repository. You just
need to run it on a server to get it to work.

**Comment by dejifemi** [comment]
Ok will do. Thanks.
