### ISSUE TITLE
Error: failed to fetch: (404) Not Found, from url: http://localhost:3000/models/face_landmark_68_model-weights_manifest.json

### ISSUE THREAD

**Issue by Glunky** [WebDevSimplified/Face-Detection-JavaScript#10]
Hi!.
So i dont know why, but   `<script defer src="../face-api.min.js" type="text/html"></script>` didnt work for me like in [this issue](https://github.com/WebDevSimplified/Face-Detection-JavaScript/issues/8).

But i did like that:
```
const fapi = require('../../face-api.min')
...
Promise.all([fapi.nets.tinyFaceDetector.loadFromUri('../../models'),
  fapi.nets.faceLandmark68Net.loadFromUri('../../models')
])
```
And it works but in browser i get an error: `Error: failed to fetch: (404) Not Found, from url: http://localhost:3000/models/tiny_face_detector_model-weights_manifest.json`

Structure of my project is
```
---------->master
--------------->examples
-------------------->example1
------------------------->client.js (analog of your script.js)
--------------->models
------------------->your_models
--------------->html
-------------------->index.html
```
-----------
What am i doing wrong?

**Comment by WebDevSimplified** [comment]
You need to match your paths to the models to the path that matches your
folder structure. Your folder structure is very different than this project
so you will need to use a path that matches your structure or change your
folder structure.

**Comment by ashique12009** [comment]
Could you tell me, what is the event name that is fired if face is detected properly?
Also it will be better if you show the code to capture the image if face is detected.
Thank you.

**Comment by Studentabhishek** [comment]
if you show the code to capture the image if face is detected.

**Comment by vishaldhull09** [comment]
Hi @Glunky 
have you solved this issue , I am also facing it

**Comment by AjeelAhmed1998** [comment]
@Glunky @vishaldhull09 did you ever figure out the solution?
