### ISSUE TITLE
README text error

### ISSUE THREAD

**Issue by bramses** [WebDevSimplified/Face-Detection-JavaScript#16]
## navigator.getUserMedia

> navigator.getUserMedia is now deprecated and is replaced by navigator.getUserMedia. To fix this bug replace all versions of navigator.mediaDevices.getUserMedia with navigator.mediaDevices.getUserMedia

should be

> navigator.getUserMedia is now deprecated and is replaced by navigator.mediaDevices.getUserMedia. To fix this bug replace all versions of navigator.getUserMedia with navigator.mediaDevices.getUserMedia

**Comment by WebDevSimplified** [comment]
🤦‍♂ 
Thanks for catching that. I just updated it.
