### ISSUE TITLE
Tried Cloning and Running index.html in Chrome http Errors CORS

### ISSUE THREAD

**Issue by laefsky** [WebDevSimplified/Face-Detection-JavaScript#20]
I tried cloning the git, opening in a directory in windows and opening the files of the form file://C:....
in Chrome (like index.html) and ran into http: and CORS(?) errors how do I run this project locally on my browser?

**Comment by WebDevSimplified** [comment]
You need to run this in a server, such as live server in VSCode. I have a
comment pinned on the video explaining this.
