### ISSUE TITLE
Hi, I am experiencing an issue. When I Downloaded the files and ran it I got a blank white screen pls help

### ISSUE THREAD

**Issue by Venexs** [WebDevSimplified/Face-Detection-JavaScript#25]
Hi, I am experiencing an issue. When I Downloaded the files and ran it I got a blank white screen pls help

**Comment by dipanshujha** [comment]
getUserMedia() is a promises, use .then() in the startVideo()

Replace this code in startVideo() function and it will work fine.

_navigator.mediaDevices.getUserMedia({video: {}}) .then((stream)=> {video.srcObject = stream;}, (err)=> console.error(err));_
