### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Nanodayo23** [WebDevSimplified/Face-Detection-JavaScript#3]
Hello, I would like to know why am I getting this error when launching it with the live server of Visual Studio Code:

navigator.getUserMedia is not a function .

Thank you in advance

**Comment by WebDevSimplified** [comment]
This works just fine for me using Chrome version 75.0.3770.142. What browser are you using? Also what URL are you accessing the site from when you load it?

**Comment by Nanodayo23** [comment]
Yes, it could correctly run on chrome and it is hosted in the URL 'http://127.0.0.1:5500/index.html'

**Comment by maessmit** [comment]
and if a newer version?

**Comment by maessmit** [comment]
Hello Mate,
But if you have a newer version?

thank you in advance
