### ISSUE TITLE
 the tensor should have 25 values but has 21

### ISSUE THREAD

**Issue by sepulm01** [WebDevSimplified/Face-Detection-JavaScript#4]
Hi, I try to use in an other folder al root dir called /face but I think this error is relate to other reasons:
Console log:
face-api.min.js:1 Uncaught (in promise) Error: Based on the provided shape, [25], the tensor should have 25 values but has 21
    at D (face-api.min.js:1)
    at Ge (face-api.min.js:1)
    at e (face-api.min.js:1)
    at jc (face-api.min.js:1)
    at face-api.min.js:1
    at Array.forEach (<anonymous>)
    at face-api.min.js:1
    at Array.forEach (<anonymous>)
    at face-api.min.js:1
    at face-api.min.js:1

**Comment by mrjizz** [comment]
same thing here trying to use tinyfacedetector

`"Uncaught (in promise) Error: Based on the provided shape, [25], the tensor should have 25 values but has 21"`

` await faceapi.nets.tinyFaceDetector.loadFromUri('/models')`

**Comment by valentinbdv** [comment]
Same for me! I can't find a way to avoid that error.
