### ISSUE TITLE
Getting nothing on screen

### ISSUE THREAD

**Issue by jatin711-debug** [WebDevSimplified/Face-Detection-JavaScript#43]
I used console.log() inside the video eventListener and I got nothin which means the video element is not picking up its event. it does not matter if i use video.addEventListener('play') or  video.addEventListener('playing') in both cases am getting no response and none my console statement. Moreover, there are no errors displayed in the console tab.
My camera is working too. I allowed all permission for enabling the camera access and also on top on chrome it says that the camera is being in use. Means everything is fine the main problem is in Event.

**Comment by Alqio** [comment]
The problem is that `MediaDevices.getUserMedia()` does not use callbacks, it uses promises. So the correct syntax for start video is now

```
const startVideo = async () => {

    try {
        video.srcObject = await navigator.mediaDevices.getUserMedia({
            video: true,
            audio: false
        })

    } catch (e) {
        console.error(e)
    }

}

```
