### ISSUE TITLE
Webcam is loading, but canvas/face recognision isnt

### ISSUE THREAD

**Issue by TetieWasTaken** [WebDevSimplified/Face-Detection-JavaScript#46]
This is my directory:
![Schermafbeelding 2021-04-28 om 10 03 30](https://user-images.githubusercontent.com/74485845/116370970-37404e80-a80b-11eb-9d6a-6b2674318406.png)

**Comment by aspectxlol** [comment]
in the script.js i changed the .then(startVideo) to .then(startVideo())
but the recognition ans stuff isnt showing up for me

**Comment by ccdejene** [comment]
check the positions of the elements, like the video and de canvas the append event has to be appending the canvas inside the video element

**Comment by Shubbair** [comment]
check the path of script or the spell of it

**Comment by Daniel-Sogbey** [comment]
var video = document.getElementById("video");

Promise.all([
	faceapi.nets.tinyFaceDetector.loadFromUri("/models"),
	faceapi.nets.faceLandmark68Net.loadFromUri("/models"),
	faceapi.nets.faceRecognitionNet.loadFromUri("/models"),
	faceapi.nets.faceExpressionNet.loadFromUri("/models")
]).then(startVideo());

console.log(video);
video.setAttribute("playsinline", "");
video.setAttribute("autoplay", "");
video.setAttribute("muted", "");
video.style.width = "200px";
video.style.height = "200px";

/* Setting up the constraint */
var facingMode = "user"; // Can be 'user' or 'environment' to access back or front camera (NEAT!)
var constraints = {
	audio: false,
	video: {
		facingMode: facingMode
	}
};

/* Stream it to video element */
const startVideo = () => {
	navigator.mediaDevices
		.getUserMedia(constraints)
		.then(function success(stream) {
			video.srcObject = stream;
		});
};
