### ISSUE TITLE
error(and when i even try using your index and javascript it produces the same error)

### ISSUE THREAD

**Issue by foluwright** [WebDevSimplified/Face-Detection-JavaScript#5]
![image](https://user-images.githubusercontent.com/49768316/65408328-fc667100-ddb2-11e9-8169-dd0bb30b08b6.png)
it keeps giving me that error

**Comment by WebDevSimplified** [comment]
It looks like whatever you are using to host your server does not host the model files on the server. You may need to configure your server to load those files or link to them in another way.

**Comment by foluwright** [comment]
How else can i link the files.
if i link it with **await** will it work, if it will how can i do that

**Comment by WebDevSimplified** [comment]
I am not sure how your server is setup locally so I am not sure. If you use live server with VSCode you shouldn't have this issue.

**Comment by fraaguilera** [comment]
i used XAAMP and don't work, i try with live server too but the sames error too.

**Comment by WebDevSimplified** [comment]
I am not sure what the error is then. I am really sorry. It could be possible your files are not in the right folders and that is why they cannot be found.

**Comment by foluwright** [comment]
i also tried live severs, it didn't work
