### ISSUE TITLE
Error - Expected box to be IBoundingBox

### ISSUE THREAD

**Issue by Bezly** [WebDevSimplified/Face-Detection-JavaScript#6]
![image](https://user-images.githubusercontent.com/44766117/65600797-811ae000-dfa9-11e9-9d6c-dbd9c9583d0a.png)

Hi,
Thank for your work! 
I am faced with Error, that you can see above. 

Could you help with this?

Best Regards,
Bezly

**Comment by WebDevSimplified** [comment]
I am not sure what this error is. Are you sure your code is the same as the code in this repo?

**Comment by aboule** [comment]
hi am facing the same error please i need your help

**Comment by felipebutcher** [comment]
I was having this error when running the html served in a node environment. Running it from traditional apache works fine.
