### ISSUE TITLE
Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by emmalex2** [WebDevSimplified/Face-Detection-JavaScript#7]
video.addEventListener('play', () => {
  setInterval(async () => {
     const detections = await faceapi.dectectAllFaces(video,
      new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks
     ().withFaceExpressions()
     console.log(detections)
  }, 100)
})

and when i reload chrome and check inspect the project it shows this errror ( Uncaught (in promise) TypeError: faceapi.dectectAllFaces is not a function) the  code is above
please i need yout help

**Comment by WebDevSimplified** [comment]
You spelled detect wrong.

**Comment by emmalex2** [comment]
thanks

**Comment by emmalex2** [comment]
but am having another error 


Uncaught (in promise) Error: Dimensions.constructor - expected width and height to be valid numbers, instead have {"width":720}
    at new t (face-api.min.js:1)
    at Object.e [as resizeResults] (face-api.min.js:1)

this is the code 

video.addEventListener('play', () => {
  const canvas = faceapi.createCanvasFromMedia(video)
  document.body.append(canvas)
  const displaySize = {width:  video.width, hegiht: video.height}
  setInterval(async () => {
     const detections = await faceapi.detectAllFaces(video,
      new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks
     ().withFaceExpressions()
     console.log(detections)
     const resizedDetections = faceapi.resizeResults(detections,
     displaySize)
     faceapi.draw.drawDetections(canvas, resizedDetections)
  }, 100)
})

**Comment by WebDevSimplified** [comment]
You have height spelled wrong in your displaySize variable.

**Comment by gabi-dev-tech** [comment]
I have the same error as @AuthorMremmalex ,   can anybody help me?
